openapi: 3.0.1
info:
  title: Auth Server [DEV ONLY]
  description: Auth server for boatnet.
  version: 1.0.1
servers:
  - url: /api/v1
tags:
  - name: Login
    description: Login Routines
  - name: User Info
    description: Get User Info + Details
  - name: User Management
    description: User Management
  - name: Roles
    description: Roles Management

paths:
  /login:
    post:
      tags:
        - Login
      summary: Perform login to get JWT token
      operationId: postLogin
      requestBody:
        description: Need username and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
            examples:
              Encoded:
                value:
                  username: 'test'
                  passwordEnc: 'dGVzdA=='
                  applicationName: 'BOATNET_OBSERVER'
              Basic:
                value:
                  username: 'test'
                  password: 'test'
        required: true
      responses:
        '200':
          description: 'User Authorized'
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  token:
                    type: string
                    description: 'JWT encoded token'
              example:
                username: 'test'
                token: '(JWT Token - decode at jwt.io)'
        '401':
          description: 'Authorization information is missing or invalid.'
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  status:
                    type: integer
                    format: int64
                  message:
                    type: string
              example:
                status: 401
                message: 'You have not been granted access to this application.'

  /pubkey:
    get:
      tags:
        - Login
      summary: Get RSA key for JWT validation
      description: Returns public RSA key
      operationId: getPubkey
      responses:
        '200':
          description: Retrieved Public RSA Key OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keys'
              example:
                kty: 'RSA'
                e: '(JWK Encoded Key)'
                n: 'AQAB'
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Info
      summary: Get Users (Roles Read Access)
      description: Get application users
      operationId: getUsers
      parameters:
        - in: query
          name: applicationName
          schema:
            type: string
            default: 'BOATNET_OBSERVER'
          description: Application Name
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  users:
                    type: array
                    items:
                      type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /users-details:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Info
      summary: Get All User Details (Roles Read Access)
      description: Get application users details
      operationId: getUsersDetails
      parameters:
        - in: query
          name: applicationName
          schema:
            type: string
            default: 'BOATNET_OBSERVER'
          description: Application Name
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  applicationName:
                    type: string
                    example: 'BOATNET_OBSERVER'
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email_address:
                          type: string
                        phone:
                          type: string
                        org:
                          type: string
                        division:
                          type: string

                    example:
                      -
                        user_id: 'seabass.mcgillicutty'
                        first_name: 'Seabass'
                        last_name: 'McGillicutty'
                        email_address: 'test@test.com'
                        phone: '123-456-7890'
                        org: null
                        division: 'FRAM'


        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /roles:
    get:
      security:
        - bearerAuth: []
      tags:
        - Roles
      summary: Get All Roles (Roles Read Access)
      description: Get all application roles
      operationId: getRoles
      parameters:
        - in: query
          name: applicationName
          schema:
            type: string
            default: 'BOATNET_OBSERVER'
          description: Application Name
      responses:
        '200':
          description: Roles
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  users:
                    type: array
                    items:
                      type: string
              example:
                roles: ['observer', 'debriefer', 'every-other-role...']
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /user:
    post:
      security:
        - bearerAuth: []
      tags:
        - User Management
      summary: Add New User (Roles Admin)
      description: Create a boatnet user
      operationId: postUser
      requestBody:
        description: New User info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUser'
        required: true
      responses:
        '200':
          description: New User Created
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  userId:
                    type: number
              example:
                username: 'seabass.mcgillicutty'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      security:
        - bearerAuth: []
      tags:
        - User Management
      summary: Delete User (Roles Admin)
      description: Delete a boatnet user from one or all applications
      operationId: delUser
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username to delete
          example: 'jane.doe'
        - in: query
          name: applicationName
          schema:
            type: string
            default: 'ALL'
          required: false
          description: Remove access to one specific application (all roles) or 'ALL' to remove user entirely
          example: 'ALL'

      responses:
        '200':
          description: User Deleted
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  applicationName:
                    type: string
                  result:
                    type: string
              example:
                username: 'seabass.mcgillicutty'
                applicationName: 'BOATNET_OBSERVER'
                result: 'User removed from BOATNET_OBSERVER application(s).'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user-role:
    get:
      security:
        - bearerAuth: []
      tags:
        - Roles
        - User Info
      summary: Get a User's Roles (Roles Read Access)
      description: Get roles for existing user
      operationId: getUserRole
      parameters:
        - in: query
          name: username
          description: Username to get roles for
          required: true
          schema:
            type: string
          example: 'jane.doe'
        - in: query
          name: applicationName
          schema:
            type: string
            default: 'BOATNET_OBSERVER'
          description: Application Name
      responses:
        '200':
          description: User Roles
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  applicationName:
                    type: string
                  username:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
              example:
                username: 'seabass.mcgillicutty'
                roles: ['admin', 'captain']
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      security:
        - bearerAuth: []
      tags:
        - Roles
      summary: Add New User Role (Roles Admin)
      description: Add a role to existing user
      operationId: postUserRole
      requestBody:
        description: User + new Role info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUserRole'
        required: true
      responses:
        '200':
          description: Role Added
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  applicationName:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
              example:
                username: 'seabass.mcgillicutty'
                roles: ['admin', 'captain']
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      security:
        - bearerAuth: []
      tags:
        - Roles
      summary: Delete User Role(Roles Admin)
      description: Remove a role from existing user
      operationId: delUserRole
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username to delete
        - in: query
          name: role
          schema:
            type: string
          required: true
          description: Role to delete
        - in: query
          name: applicationName
          schema:
            type: string
            default: 'BOATNET_OBSERVER'
          required: false
          description: Application name to remove role from
          example:
            username: 'jane.doe'
            role: 'captain'
            applicationName: 'BOATNET_OBSERVER'
      responses:
        '200':
          description: Role Deleted
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
                  applicationName:
                    type: string
              example:
                username: 'seabass.mcgillicutty'
                roles: ['captain']
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user-role-status:
    put:
      security:
        - bearerAuth: []
      tags:
        - Roles
      summary: Enable or Disable User Role (Roles Admin)
      description: Enable/disable role of existing user
      operationId: postUserRoleStatus
      requestBody:
        description: User, Role, enable flag
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRoleStatus'
        required: true
      responses:
        '200':
          description: Role Status Updated
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
                  applicationName:
                    type: string
              example:
                username: 'seabass.mcgillicutty'
                roles: ['admin', 'captain']
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user-details:
    put:
      security:
        - bearerAuth: []
      tags:
        - User Management
      summary: Update User Details (Roles Admin)
      description: Update a user's details, either org, phone, or email_address
      operationId: postUserDetails
      requestBody:
        description: Updated User info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
        required: true
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  keyValues:
                    type: array
                    items:
                      type: object
              example:
                username: 'seabass.mcgillicutty'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      security:
        - bearerAuth: []
      tags:
        - User Info
      summary: Get Single User Details (Roles Read Access)
      description: Get application users details
      operationId: getUserDetails
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username
      responses:
        '200':
          description: User Details [TBD]
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                    example: 'seabass.mcgillicutty'
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        column_name:
                          type: string
                        value:
                          type: string


                    example:
                      -
                        column_name: 'LAST_NAME'
                        value: 'McGillicutty'

        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /test-auth:
    post:
      tags:
        - Login
      summary: Checks JWT token validity
      description: Check JWT auth
      operationId: postTestAuth
      requestBody:
        description: JWT Token
        content:
          application/json:
            schema:
              type: 'object'
              properties:
                token:
                  type: string
            example:
              token: '(jwt value)'
        required: false
      responses:
        '200':
          description: JWT OK
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
              example:
                user: 'test'
                roles: ['test']
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    get:
      security:
        - bearerAuth: []
      tags:
        - Login
      summary: Check JWT token validity - Bearer Auth
      description: Check JWT auth
      operationId: getTestAuth2
      responses:
        '200':
          description: JWT OK
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  username:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
              example:
                user: 'test'
                roles: ['test']
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    Keys:
      type: object
      properties:
        keys:
          type: array
          items:
            type: object
            properties:
              kty:
                type: string
              e:
                type: string
              n:
                type: string
                description: JWK Encoded PEM Public Key
    Login:
      type: object
      required:
        - username
      properties:
        username:
          type: string
        password:
          type: string
          description: Required if passwordEnc not specified
        passwordEnc:
          type: string
          description: Required if password not specified
        encodeCouchPassword:
          type: boolean
          description: Base64 encode couch password
        clientVersion:
          type: string
          description: Optional (recommended) client version info
        applicationName:
          type: string
          description: Application name, determines which roles are returned in JWT
          default: 'BOATNET_OBSERVER'
    AddUser:
      type: object
      required:
        - username
        - lastName
        - firstName
        - emailAddress
      properties:
        username:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        emailAddress:
          type: string
        comment:
          type: string
      example:
        username: 'jane.doe'
        lastName: 'Doe'
        firstName: 'Jane'
        emailAddress: 'bad@address.xyz'
        comment: 'This is an example user.'
    AddUserRole:
      type: object
      required:
        - username
        - role
      properties:
        applicationName:
          type: string
          default: 'BOATNET_OBSERVER'
        username:
          type: string
        role:
          type: string
      example:
        username: 'jane.doe'
        role: 'captain'
    UpdateUser:
      type: object
      required:
        - username
        - keyValues
      properties:
        username:
          type: string
        keyValues:
          type: object
          properties:
            org:
              type: string
            phone:
              type: string
            email_address:
              type: string
      example:
        username: 'jane.doe'
        keyValues:
          phone: '123-123-1234'
          org: 'FRAM'
    UserRoleStatus:
      type: object
      required:
        - username
        - role
        - enable
      properties:
        applicationName:
          type: string
          default: 'BOATNET_OBSERVER'
        username:
          type: string
        role:
          type: string
        enable:
          type: boolean
      example:
        username: 'jane.doe'
        role: 'captain'
        enable: false
    Error:
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
      example:
        status: 401
        message: 'Unauthorized'
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: 'object'
            properties:
              status:
                type: integer
                format: int64
              message:
                type: string
          examples:
            Malformed:
              value:
                status: 401
                message: 'jwt malformed'
              summary: 'JWT malformed'
            Expired:
              value:
                status: 401
                message: 'jwt expired'
              summary: 'JWT lifetime expired'
            InvalidSignature:
              value:
                status: 401
                message: 'invalid signature'
              summary: 'JWT signed with different private key'
            InsufficientPrivs:
              value:
                status: 401
                message: 'Insufficient role privileges'
              summary: 'User does not have required role'
    NotFoundError:
      description: No data found
      content:
        application/json:
          schema:
            type: 'object'
            properties:
              status:
                type: integer
                format: int64
              message:
                type: string
          example:
            status: 404
            message: 'Not Found'
